/* tslint:disable */
/* eslint-disable */
/**
 * Trading212 Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Account
 */
export interface Account {
    /**
     * ISO 4217
     * @type {string}
     * @memberof Account
     */
    currencyCode?: string;
    /**
     * 
     * @type {number}
     * @memberof Account
     */
    id?: number;
}

/**
 * Check if a given object implements the Account interface.
 */
export function instanceOfAccount(value: object): value is Account {
    return true;
}

export function AccountFromJSON(json: any): Account {
    return AccountFromJSONTyped(json, false);
}

export function AccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): Account {
    if (json == null) {
        return json;
    }
    return {
        
        'currencyCode': json['currencyCode'] == null ? undefined : json['currencyCode'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function AccountToJSON(value?: Account | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'currencyCode': value['currencyCode'],
        'id': value['id'],
    };
}

