/* tslint:disable */
/* eslint-disable */
/**
 * Trading212 Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Tax
 */
export interface Tax {
    /**
     * 
     * @type {string}
     * @memberof Tax
     */
    fillId?: string;
    /**
     * 
     * @type {string}
     * @memberof Tax
     */
    name?: TaxNameEnum;
    /**
     * 
     * @type {number}
     * @memberof Tax
     */
    quantity?: number;
    /**
     * 
     * @type {Date}
     * @memberof Tax
     */
    timeCharged?: Date;
}


/**
 * @export
 */
export const TaxNameEnum = {
    CommissionTurnover: 'COMMISSION_TURNOVER',
    CurrencyConversionFee: 'CURRENCY_CONVERSION_FEE',
    FinraFee: 'FINRA_FEE',
    FrenchTransactionTax: 'FRENCH_TRANSACTION_TAX',
    PtmLevy: 'PTM_LEVY',
    StampDuty: 'STAMP_DUTY',
    StampDutyReserveTax: 'STAMP_DUTY_RESERVE_TAX',
    TransactionFee: 'TRANSACTION_FEE'
} as const;
export type TaxNameEnum = typeof TaxNameEnum[keyof typeof TaxNameEnum];


/**
 * Check if a given object implements the Tax interface.
 */
export function instanceOfTax(value: object): value is Tax {
    return true;
}

export function TaxFromJSON(json: any): Tax {
    return TaxFromJSONTyped(json, false);
}

export function TaxFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tax {
    if (json == null) {
        return json;
    }
    return {
        
        'fillId': json['fillId'] == null ? undefined : json['fillId'],
        'name': json['name'] == null ? undefined : json['name'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'timeCharged': json['timeCharged'] == null ? undefined : (new Date(json['timeCharged'])),
    };
}

export function TaxToJSON(value?: Tax | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'fillId': value['fillId'],
        'name': value['name'],
        'quantity': value['quantity'],
        'timeCharged': value['timeCharged'] == null ? undefined : ((value['timeCharged']).toISOString()),
    };
}

